type DataType = {
  name: string;
  dataType: string;
  unique: boolean;
  asTitle: boolean;
  search: boolean;
  fullText: boolean;
  showList: boolean;
}

export const defaults: {[key: string]: DataType} = {
  text: {
    name: 'text',
    dataType: 'text',
    unique: false,
    asTitle: false,
    search: true,
    fullText: false,
    showList: true,
  },
  textarea: {
    name: 'textarea',
    dataType: 'textarea',
    unique: false,
    asTitle: false,
    search: true,
    fullText: false,
    showList: true,
  },
  number: {
    name: 'number',
    dataType: 'number',
    unique: false,
    asTitle: false,
    search: true,
    fullText: false,
    showList: true,
  },
  select: {
    name: 'select',
    dataType: 'select',
    unique: false,
    asTitle: false,
    search: true,
    fullText: false,
    showList: true,
  },
  radio: {
    name: 'radio',
    dataType: 'radio',
    unique: false,
    asTitle: false,
    search: true,
    fullText: false,
    showList: true,
  },
  checkbox: {
    name: 'checkbox',
    dataType: 'checkbox',
    unique: false,
    asTitle: false,
    search: true,
    fullText: false,
    showList: true,
  },
  autonum: {
    name: 'autonumber',
    dataType: 'autonum',
    unique: true,
    asTitle: false,
    search: true,
    fullText: false,
    showList: true,
  },
  calc: {
    name: 'calculation',
    dataType: 'calc',
    unique: false,
    asTitle: false,
    search: true,
    fullText: false,
    showList: true,
  },
  datetime: {
    name: 'datetime',
    dataType: 'datetime',
    unique: false,
    asTitle: false,
    search: true,
    fullText: false,
    showList: true,
  },
  file: {
    name: 'file',
    dataType: 'file',
    unique: false,
    asTitle: false,
    search: false,
    fullText: false,
    showList: true,
  },
  users: {
    name: 'user',
    dataType: 'users',
    unique: false,
    asTitle: false,
    search: true,
    fullText: false,
    showList: true,
  },
  dslookup: {
    name: 'dslookup',
    dataType: 'dslookup',
    unique: false,
    asTitle: false,
    search: true,
    fullText: false,
    showList: true,
  },
  label: {
    name: 'label',
    dataType: 'label',
    unique: false,
    asTitle: false,
    search: false,
    fullText: false,
    showList: false,
  },
  separator: {
    name: 'separator',
    dataType: 'separator',
    unique: false,
    asTitle: false,
    search: false,
    fullText: false,
    showList: false,
  },
}
